import styles from "@/styles/Home.module.scss";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <section className={styles.container}>
      <Head>
        <title>Rendering Strategies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul className={styles.list}>
        <li className={styles.item}>
          <Link href="/client" prefetch={false}>
            CSR
          </Link>
        </li>
        <li className={styles.item}>
          <Link href="/server" prefetch={false}>
            SSR
          </Link>
        </li>
        <li className={styles.item}>
          <Link href="/static" prefetch={false}>
            SSG
          </Link>
        </li>
      </ul>
    </section>
  );
}
