import styles from "@/styles/Home.module.scss";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <section className={styles.container}>
      <Head>
        <title>Rendering Strategies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul className={styles.list}>
        <li className={styles.item}>
          <Link href="/client">
            <abbr title="Client Side Rendering">CSR</abbr>
          </Link>
        </li>
        <li className={styles.item}>
          <Link href="/server">
            <abbr title="Server Side Rendering">SSR</abbr>
          </Link>
        </li>
        <li className={styles.item}>
          <Link href="/static">
            <abbr title="Static Site Generation">SSG</abbr>
          </Link>
        </li>
      </ul>
    </section>
  );
}
